//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachSanPham
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string hinhanh { get; set; }
        public Nullable<int> dongia { get; set; }
        public Nullable<int> madm { get; set; }
    }
}
