//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebBanHangEntities : DbContext
    {
        public WebBanHangEntities()
            : base("name=WebBanHangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acc> Acc { get; set; }
        public virtual DbSet<DanhMucSanPham> DanhMucSanPham { get; set; }
        public virtual DbSet<DanhSachSanPham> DanhSachSanPham { get; set; }
    
        public virtual int DeleteProduct(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteProduct", idParameter);
        }
    
        public virtual int InsertProduct(string ten, string hinhanh, Nullable<decimal> dongia, Nullable<int> madm)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            var madmParameter = madm.HasValue ?
                new ObjectParameter("madm", madm) :
                new ObjectParameter("madm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("InsertProduct", tenParameter, hinhanhParameter, dongiaParameter, madmParameter);
        }
    
        public virtual int UpdateProduct(Nullable<int> id, string ten, string hinhanh, Nullable<decimal> dongia, Nullable<int> madm)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var hinhanhParameter = hinhanh != null ?
                new ObjectParameter("hinhanh", hinhanh) :
                new ObjectParameter("hinhanh", typeof(string));
    
            var dongiaParameter = dongia.HasValue ?
                new ObjectParameter("dongia", dongia) :
                new ObjectParameter("dongia", typeof(decimal));
    
            var madmParameter = madm.HasValue ?
                new ObjectParameter("madm", madm) :
                new ObjectParameter("madm", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateProduct", idParameter, tenParameter, hinhanhParameter, dongiaParameter, madmParameter);
        }
    }
}
